config/urls.py
from pathlib import Path

from allauth.core.internal.httpkit import redirect
from django.contrib import admin
from django.views.static import serve
from django.urls import path, re_path, include, reverse
from django.urls import path, re_path, include
from django.http.response import HttpResponse


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("signin/", lambda request: redirect(f"{reverse('spezspellz:login')}?next={request.GET.get('next', '')}"), name="login"),
    path('health', lambda _: HttpResponse("Healthy")),
    path('', include("spezspellz.urls", namespace="spsp")),
    re_path(r"^assets/(?P<path>.*)$", serve, {
        'document_root':
        Path(__file__).parents[1].joinpath("assets")
    })
]

spezspellz/urls.py
"""This file contains urls of SpezSpellz."""
from django.urls import path
import spezspellz.views as views


app_name = "spezspellz"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("signup/", views.RegisterView.as_view(), name="register"),
    path("upload/", views.UploadPage.as_view(), name="upload"),
    path("edit/<int:spell_id>/", views.UploadPage.as_view(), name="edit"),
    path("settings/", views.UserSettingsPage.as_view(), name="usersettings"),
    path("tags/", views.TagsPage.as_view(), name="tags"),
    path("tags/reqs/", views.TagsPage.as_view(), name="tags_reqs"),
    path("attachment/<int:attachment_id>/", views.attachment_view, name="attachments"),
    path("spell/<int:spell_id>/", views.SpellPage.as_view(), name="spell"),
    path("spell/thumbnail/<int:spell_id>/", views.thumbnail_view, name="spell_thumbnail"),
    path("profile/", views.profile_view, name="profile"),
    path("profile/<int:user_id>", views.other_profile_view, name="other_profile"),
    path("profile/spells/", views.profile_spells_view, name="profile_spells"),
    path("profile/spells/<int:user_id>/", views.profile_spells_view, name="profile_spells"),
    path("filter/", views.FilterPage.as_view(), name="filter"),
    path("avatar/<int:user_id>/", views.profile_picture_view, name="avatar"),
    path("notifications/", views.NotificationView.as_view(), name="notifications")
]

websocket_urlpatterns = [
    path("<str:channels>/", views.RealtimeConsumer.as_asgi(), name="ws"),
    path("", views.RealtimeConsumer.as_asgi(), name="ws")
]

spezspellz/models/spell.py
"""Implements Spell model."""
from datetime import datetime
from typing import cast, Any
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Avg
from .category import Category


class Spell(models.Model):
    """The model that stores spells."""

    creator: models.ForeignKey[User] = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    title: models.CharField = models.CharField(max_length=50)
    data: models.CharField = models.CharField(max_length=4096 * 10)
    thumbnail: models.FileField = models.FileField(
        upload_to="content", null=True
    )
    category: models.ForeignKey[Category] = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL
    )
    date: models.DateField = models.DateField(default=datetime.today)

    def __str__(self) -> str:
        """Return the spell title."""
        return str(self.title)

    @property
    def sorted_tags(self):
        """Return HasTag objects sorted by rating descending."""
        return self.hastag_set.order_by("-rating")

    def calc_avg_stars(self) -> float:
        """Calculate average stars for a spell."""
        avg_star = cast(Any, self).review_set.aggregate(Avg('star'))['star__avg']
        if avg_star is None:
            avg_star = 9
        return round(avg_star * .5 + .5, 2)

    def calc_category_rating(self) -> int:
        """Calculate the category rating."""
        return cast(Any, self).ratecategory_set.filter(positive=True).count(
        ) - cast(Any, self).ratecategory_set.filter(positive=False).count()

    @property
    def summary(self):
        """Find a possible summary of the spell."""
        start = self.data.find("is ") or 0
        end = start + (self.data[start:].find(".") or (len(self.data) - start))
        return self.data[start:end].replace("#", "")

    @property
    def tried(self) -> int:
        """Returns the spell tried."""
        return cast(Any, self).successrate_set.all().count()

    @property
    def success_rate(self) -> float:
        """Calculates percentage of positive of total."""
        avg_rating = cast(Any, self).successrate_set.filter(spell=self) \
            .aggregate(Avg('rating'))['rating__avg']
        if avg_rating is None:
            return 100.0
        return (avg_rating / 4) * 100

spezspellz/models/tag.py
"""Implements Tag model."""
from django.db import models

TAG_COLORS = (
    '#e6194b', '#3cb44b', '#ffe119',
    '#4363d8', '#f58231', '#911eb4',
    '#46f0f0', '#f032e6', '#bcf60c',
    '#fabebe', '#008080', '#e6beff',
    '#9a6324', '#fffac8', '#800000',
    '#aaffc3', '#808000', '#ffd8b1',
    '#808080', '#ffffff'
)


class Tag(models.Model):
    """The tag."""

    name: models.CharField = models.CharField(max_length=50, unique=True)

    def __str__(self):
        """Return the tag name."""
        return str(self.name)

    @property
    def color(self):
        """Return the color of the tag."""
        h = 0
        for ch in str(self.name):
            h = (((h << 5) - h) + ord(ch))
        h &= 0xFFFFFFFF
        return TAG_COLORS[h % len(TAG_COLORS)]

spezspellz/views/profile_spells_view.py
"""Implements the myspell page."""
from typing import cast, Any, Optional
from django.http import HttpRequest, HttpResponseBase, Http404
from django.shortcuts import render
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.models import User
from django.shortcuts import redirect
from spezspellz.utils import get_or_none


def profile_spells_view(request: HttpRequest, user_id: Optional[int] = None) -> HttpResponseBase:
    """View for all created spell by current user."""
    user = request.user
    if user_id is None:
        if not user.is_authenticated:
            return redirect_to_login(request.get_full_path(), "login")
        focus_user = user
    else:
        if user_id == user.pk:
            return redirect("spezspellz:profile_spells")
        other_user = get_or_none(User, pk=user_id)
        if other_user is None:
            raise Http404
        focus_user = other_user
    spells = cast(Any, focus_user).spell_set.all()
    return render(request, "profile_spells.html", {
        "spells": spells,
        "focus_user": focus_user
    })

spezspellz/views/profile_view.py
"""Implements the profile page."""
from typing import Any, cast
from django.http import HttpRequest, HttpResponseBase, Http404
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from spezspellz.models import Spell, Bookmark
from spezspellz.utils import get_or_none


@login_required
def profile_view(request: HttpRequest) -> HttpResponseBase:
    """Handle the profile page."""
    user = request.user
    spells = Spell.objects.filter(creator=user)
    bookmarks = Bookmark.objects.filter(user=user)
    history = cast(Any, user).spellhistoryentry_set.order_by("-time")
    context = {
        'user': user,
        'spells': spells,
        'bookmarks': bookmarks,
        'history': history
    }
    return render(request, 'profile.html', context)


def other_profile_view(request: HttpRequest, user_id: int) -> HttpResponseBase:
    """Handle viewing other people profile page."""
    user = request.user
    if user.pk == user_id:
        return redirect("spezspellz:profile")
    other_user = get_or_none(User, pk=user_id)
    if other_user is None:
        raise Http404
    return render(request, 'profile.html', {
        'other_user': other_user,
        'spells': cast(Any, other_user).spell_set.all(),
        'bookmarks': cast(Any, other_user).bookmark_set.all(),
        'history': cast(Any, other_user).spellhistoryentry_set.order_by("-time")
    })

templates/index.html
{% extends 'base.html' %}
{% block Title %}Home - SpezSpellz{% endblock %}
{% block BeforeBody %}
<link rel="stylesheet" href="/assets/index.css">
{% endblock %}
{% block Body %}
<h1 class="sp-title">SpezSpellz</h1>
<form style="display: flex;justify-content: center;" method="get" action="{% url 'spezspellz:filter' %}" class="search-form">
  <input class="search-bar" name="s" placeholder="Cool spells" type="text"/>
  <button type="submit" class="search-button">Search</button>
</form>
{% if user.is_authenticated and recommended_spells %}
<h2 style="padding-left: 20px;">Recommended for you</h2>
<div class="strip-box">
  {% for spell in recommended_spells %}
  <a href="{% url 'spezspellz:spell' spell.pk %}"><div class="spell">
    <img src="{% url 'spezspellz:spell_thumbnail' spell.pk %}" class="spell-img"/>
    <h2 class="spell-title">{{ spell.title }}</h2>
  </div></a>
  {% endfor %}
</div>
{% endif %}
<h2 style="padding-left: 20px;">Latest posts</h2>
<div class="strip-box">
  {% for spell in latest_spells %}
  <a href="{% url 'spezspellz:spell' spell.pk %}"><div class="spell">
    <img src="{% url 'spezspellz:spell_thumbnail' spell.pk %}" class="spell-img"/>
    <h2 class="spell-title">{{ spell.title }}</h2>
  </div></a>
  {% empty %}
  <a href="{% url 'spezspellz:upload' %}" style="text-decoration: underline;">Nothing new yet, but you could create the newest one</a>
  {% endfor %}
</div>
<h2 style="padding-left: 20px;">Top rated posts</h2>
<div class="strip-box">
  {% for spell in top_rated_spells %}
  <a href="{% url 'spezspellz:spell' spell.pk %}"><div class="spell">
    <img src="{% url 'spezspellz:spell_thumbnail' spell.pk %}" class="spell-img"/>
    <h2 class="spell-title">{{ spell.title }}</h2>
  </div></a>
  {% empty %}
  <a href="{% url 'spezspellz:upload' %}" style="text-decoration: underline;">Be the first person to have a top rated post</a>
  {% endfor %}
</div>
<h2 style="padding-left: 20px;">All Posts</h2>
<div class="all-spell-container">
  {% for spell in spells %}
  <a href="{% url 'spezspellz:spell' spell.pk %}">
    <div class="all-spell">
      <img src="{% url 'spezspellz:spell_thumbnail' spell.pk %}" class="all-spell-img" alt="{{ spell.title }}"/>
      <div id="big-box" style="display: flex; flex-direction: column">
        <div id="info-box" style="display: flex; flex-direction: row">
          <div id="attribute-box" style="width: 700px;">
            <div id="title-box" style="display: flex; flex-direction: row">
              <h3 class="all-spell-title">{{ spell.title }}</h3>
              <span style="font-size: 20px; margin-left: 20px;">{{ spell.calc_avg_stars }}</span>
              <img class="star" src="/assets/star.svg"/>
            </div>
            <p class="all-spell-category">{{ spell.category }}</p>
            <p class="all-spell-creator">{{ spell.creator }}</p>
          </div>
          <div id="success-box" style="display: flex; flex-direction: column; margin-top: 21px;">
            <span class="all-spell-category"> Used by: {{ spell.tried }} people</span>
            {% if spell.tried != 0 %}
            <span class="all-spell-category success-rate" data-rate="{{ spell.success_rate }}">
                  Success rate: {{ spell.success_rate|floatformat:2 }}%</span>
            {% else %}
            <span class="all-spell-category">Not tried</span>
            {% endif %}
          </div>
        </div>
        <p class="all-spell-data">{{ spell.title }} {{ spell.summary|slice:":100" }}...</p>
      </div>
      <div class="spell-text-box" style="margin-left: auto; margin-right: 20px;">
        <span class="all-spell-category"> Creation date: {{ spell.date }}</span>
      </div>
    </div></a>
  {% empty %}
  <a href="{% url 'spezspellz:upload' %}" style="text-decoration: underline;">No posts yet, why not create one?</a>
  {% endfor %}
  {% if max_page > 1 %}
  <div class="nav-bar" style="display: flex;justify-content: center;"><ul>
    {% if cur_page != 1 %}
    <a href="{% url 'spezspellz:home' %}?page=1">&lt&lt</a>
    <a href="{% url 'spezspellz:home' %}?page={{ cur_page|add:'-1' }}">&lt</a>
    {% endif %}
    {% for page in pages %}
    <a {% if page == cur_page %}class="cur"{% else %}href="{% url 'spezspellz:home' %}?page={{ page }}"{% endif %}>{{ page }}</a>
    {% endfor %}
    {% if cur_page != max_page %}
    <a href="{% url 'spezspellz:home' %}?page={{ cur_page|add:1 }}">&gt</a>
    <a href="{% url 'spezspellz:home' %}?page={{ max_page }}">&gt&gt</a>
    {% endif %}
  </ul></div>
  {% endif %}
</div>

<!--Script for getting color depending on the success rate -->
<script src="/assets/js/successRate.js"></script>

{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block Title %}Profile - {{ user.username }}{% endblock %}

{% block BeforeBody %}
<link rel="stylesheet" href="/assets/profile.css">
{% endblock %}
{% block Body %}

<div class="cover-all">
  <div id="aboutMe" class="profile-container">
    <div id="ProfilePic" style="margin: 0 50px 0 0;">
      {% if not other_user %}
      <img style="border-radius: 50%; width: 200px; height: 200px" class="default_img" src="{% url 'spezspellz:avatar' user.pk %}"/>
      {% else %}
      <img style="border-radius: 50%; width: 200px; height: 200px" class="default_img" src="{% url 'spezspellz:avatar' other_user.pk %}"/>
      {% endif %}
    </div>

    <div id="ProfileInfo">
      {% if not other_user %}
      <span class="name"> {{ user.username }} </span>
      <p style="margin: 0;"> Joined on {{ user.date_joined }} </p>
      <p style="margin: 0;"> Success rate: {{ user.userinfo.success_rate|floatformat:2 }}% </p>
      <p style="margin: 0;"> Post(s) used by {{ user.userinfo.spells_tried }} user(s) </p>
      <hr>
      <p style="margin-top: 10px;"> {{ user.userinfo.user_desc }} </p>
      {% else %}
      <span class="name"> {{ other_user.username }} </span>
      <p style="margin: 0;"> Joined on {{ other_user.date_joined }} </p>
      <p style="margin: 0;"> Success rate: {{ other_user.userinfo.success_rate|floatformat:2 }}% </p>
      <p style="margin: 0;"> Post(s) used by {{ other_user.userinfo.spells_tried }} user(s) </p>
      <hr>
      <p style="margin-top: 10px;"> {{ other_user.userinfo.user_desc }} </p>
      {% endif %}
    </div>

  </div>

  {% if not other_user.userinfo.is_private %}
  <!-- Everything after profile -->

  <div class="spell">

    <div class="header">
      <button id="spell_btn" style="font-size: 28pt;background-color: transparent;border-style: none;color: #FFF;cursor: pointer;" onclick="window.show_tab('1')">Spell</button>
      <button id="bookmark_btn" style="font-size: 28pt;background-color: transparent;border-style: none;color: #777;cursor: pointer;" onclick="window.show_tab('2')">Bookmark</button>
      <button id="history_btn" style="font-size: 28pt;background-color: transparent;border-style: none;color: #777;cursor: pointer;" onclick="window.show_tab('3')">History</button>
    </div>

    <div id="scroll_box" style="margin-top: 20px;">

      <div id="spell_tab">
        <ul>
          <!-- Add search bar here -->

          {% for spell in spells %}
          <li my_spell="{{ spell.pk }}">
            <a href="{% url 'spezspellz:spell' spell.pk %}" class="spell-row">
              <img class="default_img" style="height: 100px; width: 100px" src="{% url 'spezspellz:spell_thumbnail' spell.pk %}">
              <div class="spell-main-box">
                <div class="title-box">
                  <span class="all-spell-title"> {{ spell.title }} </span>
                  <span style="font-size: 20px; margin-left: 20px;">{{ spell.calc_avg_stars }}</span>
                  <img class="star" src="/assets/star.svg"/>
                </div>
                <span class="all-spell-category" style="margin-top: 20px;"> {{ spell.category }} </span>
              </div>
              <div class="spell-big-box">
                <span class="all-spell-category"> Used by: {{ spell.tried }} people</span>
                {% if spell.tried != 0 %}
                <span class="all-spell-category success-rate" data-rate="{{ spell.success_rate }}">
                      Success rate: {{ spell.success_rate|floatformat:2 }}%</span>
                {% else %}
                <span class="all-spell-category">Not tried</span>
                {% endif %}
              </div>
              <div class="spell-text-box" style="margin-left: auto; margin-right: 20px;">
                <span class="all-spell-category"> Creation date: {{ spell.date }}</span>
              </div>
            </a>
            {% if not other_user %}
            <a href="{% url 'spezspellz:edit' spell.pk %}" class="btn-like edit-btn base-btn"><img class="base-img" src="/assets/edit.svg"/></a>
            <a onclick="window.delete_spell({{spell.pk}})" class="red base-btn" style="flex: 0 0 36px"><img class="base-img" src="/assets/delete.svg"/></a>
            {% endif %}
          </li>
          {% empty %}

          {% if not other_user %}
          <li style="padding-top: 10px;padding-bottom: 10px;"><p style="margin: auto;text-align: center;">You don't have any spells</p></li>
          {% else %}
          <li style="padding-top: 10px;padding-bottom: 10px;"><p style="margin: auto;text-align: center;">This user doesn't have any spells</p></li>
          {% endif %}

          {% endfor %}
        </ul>
        {% if spells|length > 5 %}
        <div style="display: flex; margin: auto;">
          {% if not other_user %}
          <a href="{% url 'spezspellz:profile_spells' %}" class="view-all btn-like" style="text-decoration: none;"> View all </a>
          {% else %}
          <a href="{% url 'spezspellz:profile_spells' other_user.pk %}" class="view-all btn-like" style="text-decoration: none;"> View all </a>
          {% endif %}
        </div>
        {% endif %}
      </div>

      <div id="bookmark_tab" hidden>
        <ul>
          {% for bookmark in bookmarks %}
          <li bookmark_spell="{{ bookmark.spell.pk }}">
            <a href="{% url 'spezspellz:spell' bookmark.spell.pk %}" class="spell-row">
              <img class="default_img" style="height: 100px; width: 100px" src="{% url 'spezspellz:spell_thumbnail' bookmark.spell.pk %}">
              <div class="spell-main-box">
                <div class="title-box">
                  <span class="all-spell-title"> {{ bookmark.spell.title }} </span>
                  <span style="font-size: 20px; margin-left: 20px;">{{ bookmark.spell.calc_avg_stars }}</span>
                  <img class="star" src="/assets/star.svg"/>
                </div>
                <span class="all-spell-category" style="margin-top: 20px;"> {{ bookmark.spell.category }} </span>
              </div>
              <div class="spell-big-box">
                <span class="all-spell-category"> Used by: {{ bookmark.spell.tried }} people</span>
                {% if bookmark.spell.tried != 0 %}
                <span class="all-spell-category success-rate" data-rate="{{ bookmark.spell.success_rate }}">
                      Success rate: {{ bookmark.spell.success_rate }}%</span>
                {% else %}
                <span class="all-spell-category">Not tried</span>
                {% endif %}
              </div>
              <div class="spell-text-box" style="margin-left: auto; margin-right: 20px;">
                <span class="all-spell-category"> Creation date: {{ bookmark.spell.date }}</span>
              </div>
            </a>
            {% if not other_user %}
            <input type="image" onclick="window.bookmark_spell(parseInt('{{ bookmark.spell.pk }}'))" class="red base-btn" src="/assets/bookmark_remove.svg"/>
            {% endif %}
          </li>
          {% empty %}
          {% if not other_user %}
            <li style="padding-top: 10px;padding-bottom: 10px;"><p style="margin: auto;text-align: center;">You don't have any bookmarks</p></li>
          {% else %}
            <li style="padding-top: 10px;padding-bottom: 10px;"><p style="margin: auto;text-align: center;">This user doesn't have any bookmarks</p></li>
          {% endif %}
          {% endfor %}
        </ul>
      </div>

      <div id="history_tab" hidden>
        <ul>
          {% for historyObj in history %}
          <li>
            <a href="{% url 'spezspellz:spell' historyObj.spell.pk %}" class="spell-row">
              <img class="default_img" style="height: 100px; width: 100px" src="{% url 'spezspellz:spell_thumbnail' historyObj.spell.pk %}">
              <div class="spell-main-box">
                <div class="title-box">
                  <span class="all-spell-title"> {{ historyObj.spell.title }} </span>
                  <span style="font-size: 20px; margin-left: 20px;">{{ historyObj.spell.calc_avg_stars }}</span>
                  <img class="star" src="/assets/star.svg"/>
                </div>
                <span class="all-spell-category" style="margin-top: 20px;"> {{ historyObj.spell.category }} </span>
              </div>
              <div class="spell-big-box">
                <span class="all-spell-category"> Used by: {{ historyObj.spell.tried }} people</span>
                {% if historyObj.spell.tried != 0 %}
                <span class="all-spell-category success-rate" data-rate="{{ historyObj.spell.success_rate }}">
                      Success rate: {{ historyObj.spell.success_rate }}%</span>
                {% else %}
                <span class="all-spell-category">Not tried</span>
                {% endif %}
              </div>
              <span style="color: #AAA; margin-left: auto; margin-right: 20px;"> {{ historyObj.time|date:"d/m/Y" }} <br> {{ historyObj.time|date:"H:i A" }} </span>
            </a>
          </li>
          {% empty %}
          {% if not other_user %}
          <li style="padding-top: 10px;padding-bottom: 10px;"><p style="margin: auto;text-align: center;">You didn't view any spell</p></li>
          {% else %}
          <li style="padding-top: 10px;padding-bottom: 10px;"><p style="margin: auto;text-align: center;">This user didn't view any spell</p></li>
          {% endif %}
          {% endfor %}
        </ul>
      </div>
    </div>

    <script>
    window.delete_spell = (spell) => {
      fetch("{% url 'spezspellz:usersettings' %}", {
            method: "POST",
            headers: {
                "X-CSRFToken": "{{ csrf_token }}"
            },
            body: JSON.stringify({
                method: "delete",
                obj_type: "spell",
                obj_id: spell
            })
        }).then(res => {
            if(!res.ok)
                return Promise.reject();
            return res.text()
        }).then(text => {
            if(text != "Object deleted")
              return;
            document.querySelector("[my_spell=\"" + spell + "\"]").remove();
            for(const obj of document.querySelectorAll("[bookmark_spell=\"" + spell + "\"]"))
              obj.remove();
        })
    }
    window.bookmark_spell = (spell) => {
        fetch("{% url 'spezspellz:usersettings' %}", {
            method: "POST",
            headers: {
                "X-CSRFToken": "{{ csrf_token }}"
            },
            body: JSON.stringify({
                method: "bookmark",
                spell_id: spell
            })
        }).then(res => {
            if(!res.ok)
                return Promise.reject();
            return res.text()
        }).then(text => {
            if(text != "Unbookmarked")
              return;
            document.querySelector("[bookmark_spell=\"" + spell + "\"]").remove();
        })
    }
    </script>

    <!-- Script for selecting tab -->
    <script>
        let selectedTab = localStorage.getItem("spell_show") || "1";

        const tabs = ["spell", "bookmark", "history"];
        window.show_tab = (tabIndex) => {
          for(let i = 0;i < tabs.length;++i) {
            const same_tab = ("" + (i + 1)) == tabIndex;
            window[`${tabs[i]}_tab`].hidden = !same_tab;
            window[`${tabs[i]}_btn`].style.color = (same_tab ? '#FFF' : '#777');
          }
          localStorage.setItem("spell_show", tabIndex);
        };

        window.show_tab(selectedTab);
    </script>

    <!--Script for getting color depending on the success rate -->
    <script src="/assets/js/successRate.js"></script>


  </div>

  {% else %}
  <div class="centered-container">
    <img src="/assets/lock.svg" style="width:200px; margin: 100px 0 50px 0;">
    <h1>This profile is private</h1>
  </div>

</div>

  {% endif %}
  {% endblock %}

templates/profile_spells.html
{% extends 'base.html' %}
{% block Title %}My Spells{% endblock %}
{% block Body %}
<link rel="stylesheet" href="/assets/profile_spells.css">
<body>
<h1 style="margin: auto; text-align: center">{% if user == focus_user %}All{% else %}{{ focus_user.username }}'s{% endif %} created spell</h1>
<form method="GET" action="{% url 'spezspellz:filter' %}">
  <input name="s" class="search-bar" placeholder="Search {% if user == focus_user %}my{% else %}{{ focus_user.username }}'s{% endif %} spell" type="text">
  <input name="creator" value="{{ focus_user.pk }}" hidden/>
  <button type="submit" hidden></button>
</form>
<br>
<div class="spell-container">
{% for spell in spells %}
  <div spell_entry="{{ spell.pk }}" class="spell">
    <a style="text-decoration: none" href="{% url 'spezspellz:spell' spell.pk %}">
      <div style="display: flex; align-items: center">
        <img src="{% url 'spezspellz:spell_thumbnail' spell.pk %}" class="spell-img" alt="{{ spell.title }}"/>
        <div>
          <h3 class="spell-title">{{ spell.title }}</h3>
          <p class="spell-category">{{ spell.category }}</p>
          <p class="spell-creator">{{ spell.creator }}</p>
          <p class="spell-data">{{ spell.title }} {{ spell.summary|slice:":100" }}...</p>
        </div>
      </div>
    </a>
    {% if user == focus_user %}
    <div class="actions">
      <button onclick="edit_spell({{ spell.pk }})" class="edit-btn btn-like action-btn"><img class="img-btn" src="/assets/edit.svg"/></button>
      <button onclick="window.delete_spell({{ spell.pk }})" class="red action-btn"><img class="img-btn" src="/assets/delete.svg"/></button>
    </div>
    {% endif %}
  </div>
{% empty %}
<br>
<h2 style="margin: auto; text-align: center">{% if user == focus_user %}You don't{% else %}{{ focus_user.username }} doesn't{% endif %} have any spells.</h2>
{% endfor %}
</div>
<script>
    edit_spell = (spell_pk) => {
        window.location.assign(`/edit/${spell_pk}/`)
    }
    window.delete_spell = (spell) => {
    fetch("{% url 'spezspellz:usersettings' %}", {
          method: "POST",
          headers: {
              "X-CSRFToken": "{{ csrf_token }}"
          },
          body: JSON.stringify({
              method: "delete",
              obj_type: "spell",
              obj_id: spell
          })
      }).then(res => {
          if(!res.ok)
              return Promise.reject();
          return res.text()
      }).then(text => {
          if(text != "Object deleted")
            return;
          document.querySelector("[spell_entry=\"" + spell + "\"]").remove();
      })
  }
</script>
</body>
{% endblock %}